stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the project..."
    - # F端gen Sie hier Ihre Befehle zum Bauen des Projekts hinzu

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - # F端gen Sie hier Ihre Befehle zum Ausf端hren der Tests hinzu

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the project..."
    - # F端gen Sie hier Ihre Befehle zum Deployen des Projekts hinzu
